# docker/dev/compose.yml
services:
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile.dev
    env_file:
      - ../../.env/.env.dev
    volumes:
      - ../../backend:/workspace/backend:cached
    ports:
      - "5000:5000"
    privileged: true
    depends_on:
      - db
      
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.dev
    env_file:
      - ../../.env/.env.dev
    volumes:
      - ../../frontend:/workspace/frontend:cached
    ports:
      - "3000:3000"
    privileged: true
    
  db:
    build:
      context: ../../db
    env_file:
      - ../../.env/.env.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"



volumes:
  postgres-data: