FROM python:3.12-slim-bullseye
WORKDIR /workspace/backend

# poetryのインストール
RUN pip install poetry

# pyproject.tomlとpoetry.lock（存在する場合）のみをコピー
COPY pyproject.toml poetry.lock* ./

# 依存関係のインストール
RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

# 残りのコードをコピー
COPY . .
  
RUN poetry install --no-root

# Flaskアプリケーションの実行
CMD ["poetry", "run", "python", "app.py"]
