FROM python:3.12-slim-bullseye
WORKDIR /workspace/backend

# poetryのインストール
RUN pip install poetry

# pyproject.tomlとpoetry.lock（存在する場合）のみをコピー
COPY pyproject.toml poetry.lock* ./

# 依存関係のインストール
RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

# 全てのコードをコピー（migrate.shを含む）
COPY . .

RUN poetry install --no-root

# マイグレーションスクリプトに実行権限を付与
RUN chmod +x migrate.sh

# Flaskアプリケーションの実行
CMD ./migrate.sh && poetry run uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
