"""auth

Revision ID: 7e35ab3d7c07
Revises: d88feea91fcf
Create Date: 2024-10-19 14:45:02.479088

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7e35ab3d7c07'
down_revision: Union[str, None] = 'd88feea91fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. まず、nullable=Trueでカラムを追加
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))

    # 2. 既存のレコードにデフォルト値を設定
    op.execute("UPDATE users SET hashed_password = 'default_password_hash' WHERE hashed_password IS NULL")
    op.execute("UPDATE users SET is_active = TRUE WHERE is_active IS NULL")
    op.execute("UPDATE users SET is_superuser = FALSE WHERE is_superuser IS NULL")

    # 3. hashed_passwordカラムをNOT NULLに変更
    op.alter_column('users', 'hashed_password', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
